########################################################################
# This file is used as a template for the docker-compose.yaml file     #
# you will find at the root of your project when running `openbotfront up` #
########################################################################

version: "3.0"
services:
  actions:
    build:
      context: ./actions
      args:
        RASA_SDK_IMAGE: ${IMAGES_CURRENT_ACTIONS}
    container_name: openbotfront-actions
    networks: ["openbotfront-network"]
    restart: always
    ports:
      - "5055:5055"
    volumes:
      - "./actions:/app/actions"
    command:
      - start
      - --debug
      - --actions
      - actions
    env_file:
      - .env

networks:
  openbotfront-network: {}